# Use the README file as a reference to customize settings.

Ad:
  fields:
    default: location.address1, user.first_name
    form: location_id, user_id, message, contact
  relationships: 
  application: Application
