production:
  access_key_id: AKIAJQQNROVXNSD4CVVQ
  secret_access_key: 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
  bucket: rentersviewnew
development:
  access_key_id: AKIAJQQNROVXNSD4CVVQ
  secret_access_key: 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
  bucket: rentersviewnew